[package]
name = "rls"
version = "0.1.0"
authors = ["Jonathan Turner <jturner@mozilla.com>"]

[dependencies]
cargo = { path = "../cargo" }
log = "0.3"
racer = { git = "https://github.com/phildawes/racer" }
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
rls-vfs = { git = "https://github.com/nrc/rls-vfs", features = ["racer-impls"] }
rustfmt = { git = "https://github.com/rust-lang-nursery/rustfmt" }
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
derive-new = "0.3"
env_logger = "0.3"
languageserver-types = { version = "0.5.0", git = "https://github.com/gluon-lang/languageserver-types" }

[dependencies.hyper]
version = "0.9"
default-features = false
